site_name: SPO-Anywhere
site_description: Install Cardano nodes anywhere with the help of NixOS
site_url: https://github.com/mlabs-haskell/spo-anywhere

repo_url: https://github.com/mlabs-haskell/spo-anywhere
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - tables
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - Getting Started:
      - Overview: getting-started/overview.md
  - Usage:
      - Configure pool: usage/configure-pool.md
      - Generating keys: usage/generate-keys.md
      - Deploy: usage/deploy.md
      - Register: usage/register-the-pool.md
  - Development:
      - development/develop.md
      - development/contributing.md
      - license.md
## Section commented out below, would be autogenerated during docs rendering
#  - NixOS Module Reference:
#      - reference/module-options/default.md

extra:
  homepage: https://mlabs-haskell.github.io/spo-anywhere
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mlabs-haskell/spo-anywhere
      name: SPO-Anywhere on Github
  generator: false # hide the line "Made with Material for MkDocs"

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; MLabs Ltd
